/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FormLazyImport = createFileRoute('/form')()
const ButtonCounterLazyImport = createFileRoute('/button-counter')()

// Create/Update Routes

const FormLazyRoute = FormLazyImport.update({
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const ButtonCounterLazyRoute = ButtonCounterLazyImport.update({
  path: '/button-counter',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/button-counter.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/button-counter': {
      id: '/button-counter'
      path: '/button-counter'
      fullPath: '/button-counter'
      preLoaderRoute: typeof ButtonCounterLazyImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  ButtonCounterLazyRoute,
  FormLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/button-counter",
        "/form"
      ]
    },
    "/button-counter": {
      "filePath": "button-counter.lazy.tsx"
    },
    "/form": {
      "filePath": "form.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
